export const MY_PRODUCTS_REQUEST="MY_PRODUCTS_REQUEST";
export const MY_PRODUCTS_SUCCESS="MY_PRODUCTS_SUCCESS";
export const MY_PRODUCTS_FAIL="MY_PRODUCTS_FAIL";

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL="UPDATE_PRODUCT_FAIL";

export const ADD_PRODUCT_REQUEST="ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL="ADD_PRODUCT_FAIL";

export const MY_ORDERS_REQUEST="MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS="MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL="MY_ORDERS_FAIL";

export const MY_STATS_REQUEST="MY_STATS_REQUEST";
export const MY_STATS_SUCCESS="MY_STATS_SUCCESS";
export const MY_STATS_FAIL="MY_STATS_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";
export const CLEAR_PRODUCT_SUCCESS="CLEAR_PRODUCT_SUCCESS";