export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL"
export const ORDER_DETAILS_FOUND="ORDER_DETAILS_FOUND"

export const ORDER_DELETE_REQUEST="ORDER_DELETE_REQUEST"
export const ORDER_DELETE_SUCCESS="ORDER_DELETE_SUCCESS"
export const ORDER_DELETE_FAIL="ORDER_DELETE_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS";
export const CLEAR_DELETE_MSG="CLEAR_DELETE_MSG";