export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOADING_USER_REQUEST="LOADING_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";

export const LOAD_ORDERS_REQUEST="LOAD_ORDERS_REQUEST";
export const LOAD_ORDERS_SUCCESS="LOAD_ORDERS_SUCCESS";
export const LOAD_ORDERS_FAIL="LOAD_ORDERS_FAIL";

export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";

export const PASS_UPDATE_REQUEST="PASS_UPDATE_REQUEST";
export const PASS_UPDATE_SUCCESS="PASS_UPDATE_SUCCESS";
export const PASS_UPDATE_FAIL="PASS_UPDATE_FAIL";

export const PROFILE_UPDATE_REQUEST="PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS="PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL="PROFILE_UPDATE_FAIL";

export const FORGOT_PASS_REQUEST="FORGOT_PASS_REQUEST";
export const FORGOT_PASS_SUCCESS="FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAIL="FORGOT_PASS_FAIL";

export const RESET_PASS_REQUEST="RESET_PASS_REQUEST";
export const RESET_PASS_SUCCESS="RESET_PASS_SUCCESS";
export const RESET_PASS_FAIL="RESET_PASS_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";
export const CLEAR_SUCCESS="CLEAR_SUCCESS";
export const CLEAR_MSG="CLEAR_MSG";
export const CLEAR_CART_MSG="CLEAR_CART_MSG";

export const ADD_TO_CART="ADD_TO_CART";